# Generated by Django 6.0.2 on 2026-02-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip",
            field=models.CharField(default="-", max_length=255),
            preserve_default=False,
        ),
    ]
