# Generated by Django 6.0.2 on 2026-02-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_address_zip"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["email"], name="store_custo_email_8208ee_idx"),
        ),
    ]
