# Generated by Django 6.0.2 on 2026-02-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_customer_store_custo_email_8208ee_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="address",
            index=models.Index(fields=["city"], name="store_addre_city_711a8f_idx"),
        ),
    ]
