# Generated by Django 6.0.2 on 2026-02-25 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_address_store_addre_city_711a8f_idx"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CartItems",
            new_name="CartItem",
        ),
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["title"]},
        ),
    ]
